### ISSUE TITLE
ASB 2018.04

### ISSUE THREAD

**Issue by MSe1969** [cm12-amami/discussion#27]
April ASB are out, no AOSP links, yet.
Seems that Google has stopped to update the 'Lollipop' branches of AOSP. This won't stop us however to back port the relevant patches.
Due to vacations (only mobile access), I can only have a look mid of next week. 
We also need to apply the Settings patch proposed by 'awl14' in the forum thread.

**Comment by Micha-Btz** [comment]
The patch from awl14 has been committed. But now we have to evaluate for every single patch if we should apply it, that really sucks.

Maybe we should think about using the work from acip team and try to get LOS 14.1/15.1 to work.

**Comment by MSe1969** [comment]
I have been doing cm-13.0 in parallel all the time, either uploading to LineageOS gerrit or reviewing the uploaded patches, as well as having a look to the cm-11.0 branch. From what I have seen, there always has been a very obvious pattern, why certain 6.0 ASB patches weren't applied to 5.1 - mainly entire repo like external/libavc not existing in LP, an application subtree in frameworks/av not present in LP. So no rocket science.
Wrt trying to get LOS 14.1 (I doubt that 15.1 is even close to be considered) to work - we can try that in parallel, let's see how far we get...

**Comment by MSe1969** [comment]
Emphasis is on **in parallel** - I don't consider this being a trivial task

**Comment by MSe1969** [comment]
:) to avoid misunderstandings: The decision, whether a MM patch is applicable to LP is no rocket science, but backporting meanwhile Oreo code and Java language structures like 'lambdas' (which require rewriting the code) really isn't fun ...

**Comment by MSe1969** [comment]
In LineageOS gerrit, the April ASB have already been uploaded for cm-11.0 and cm-13.0, so should be possible to easily pick them...

**Comment by Micha-Btz** [comment]
Android runtime
- [x] CVE-2017-13274 | A-71360761 | EoP | High | 6.0, 6.0.1, 7.0, 7.1.1, 7.1.2, 8.0, 8.1

Framework
- n/a CVE-2017-13275  | A-70808908 | ID | High | 8.0, 8.1 - not aplicable

Media framework

- [x] CVE-2017-13276 | A-70637599 | RCE | Critical | 6.0, 6.0.1, 7.0, 7.1.1, 7.1.2, 8.0, 8.1
- [x] CVE-2017-13277 | A-72165027 | RCE | Critical | 6.0, 6.0.1, 7.0, 7.1.1, 7.1.2, 8.0, 8.1
- [ ] CVE-2017-13278 | A-70546581 | EoP | High | 6.0, 6.0.1, 7.0, 7.1.1, 7.1.2, 8.0, 8.1
- [x] CVE-2017-13279 | A-68399439 | DoS | High | 6.0, 6.0.1, 7.0, 7.1.1, 7.1.2, 8.0, 8.1
- [x] CVE-2017-13280 | A-71361451 | DoS | High | 6.0, 6.0.1, 7.0, 7.1.1, 7.1.2, 8.0, 8.1

System

- n/a CVE-2017-13281 | A-71603262 | RCE | Critical | 8.0, 8.1 
- n/a CVE-2017-13282 | A-71603315 | RCE | Critical | 7.0, 7.1.1, 7.1.2, 8.0, 8.1
- n/a CVE-2017-13283 | A-71603410 | RCE | Critical | 7.0, 7.1.1, 7.1.2, 8.0, 8.1
- [x] CVE-2017-13267 | A-69479009 | RCE | Critical | 6.0, 6.0.1, 7.0, 7.1.1, 7.1.2, 8.0, 8.1
- [x] CVE-2017-13284 | A-70808273 | EoP | Critical | 6.0, 6.0.1, 7.0, 7.1.1, 7.1.2, 8.0, 8.1 
- [x] CVE-2017-13285 | A-69177126 | RCE | High | 6.0, 6.0.1, 7.0, 7.1.1, 7.1.2, 8.0, 8.1 
- n/a CVE-2017-13286 | A-69683251 | EoP | High | 8.0, 8.1
- n/a CVE-2017-13287 | A-71714464 | EoP | High | 6.0.1, 7.0, 7.1.1, 7.1.2, 8.0, 8.1
- n/a CVE-2017-13288 | A-69634768 | EoP | High | 8.0, 8.1
- n/a CVE-2017-13289 | A-70398564 | EoP | High | 6.0, 6.0.1, 7.0, 7.1.1, 7.1.2, 8.0, 8.1
- [x] CVE-2017-13290 | A-69384124 | ID | High | 6.0, 6.0.1, 7.0, 7.1.1, 7.1.2, 8.0, 8.1
- n/a CVE-2017-13291 | A-71603553 | DoS | High | 7.0, 7.1.1, 7.1.2, 8.0, 8.1

EDIT (MSe1969):
- All patches, which are N/A, are flagged accodingly
- All other relevant patches (except CVE-2017-13278) applied
- CVE-2017-13278 does not compile, yet (temp. branch cm-12.1-tmp in frameworks/av)

**Comment by Micha-Btz** [comment]
Kernel components

- n/a CVE-2017-13293 | A-62679701* | EoP | High | NFC driver - not found
- n/a CVE-2017-5754 | A-69856074* | ID | High | Memory mapping - not found
- n/a CVE-2017-16534 | A-69052594          Upstream kernel | ID | High | USB - not aplicable

Qualcomm components

- n/a CVE-2017-15822 | A-71501534          QC-CR#2123807 | RCE | Critical | WiFi
- n/a CVE-2017-17770 | A-70237684         QC-CR#2103199        [2] | EoP | High | Binder
- [x] CVE-2018-3566 | A-72957177          QC-CR#2143847 | EoP | High | WLAN
- [x] CVE-2018-3563 | A-72956842         QC-CR#2143207        [2]        [3] | EoP | High | Audio Driver
- n/a CVE-2017-13077 | A-72957017          QC-CR#2129237 | ID | High | WLAN

EDIT (MSe1969):
Only two patches applicable and applied, rest N/A (our 3.4 kernel is getting old...)

**Comment by Micha-Btz** [comment]
And Pixel ones

Framework

- [x] CVE-2017-13294 | A-71814449        [2] | ID | Moderate | 6.0, 6.0.1, 7.0, 7.1.1, 7.1.2, 8.0, 8.1
- [x] CVE-2017-13295 | A-62537081 | DoS | Moderate | 6.0, 6.0.1, 7.0, 7.1.1, 7.1.2, 8.0, 8.1

Media framework

- n/a CVE-2017-13300 | A-71567394* | DoS | High | 6.0, 6.0.1 - not publicly available
- n/a CVE-2017-13296 | A-70897454 | DoS | High | 6.0, 6.0.1 - libavc not in LP
- [x] CVE-2017-13297 | A-71766721 | DoS | High | 6.0, 6.0.1
- [x] CVE-2017-13298 | A-72117051 | DoS | High | 6.0, 6.0.1
- n/a CVE-2017-13299 | A-70897394 | DoS | High | 6.0, 6.0.1 - libavc not in LP

System
- n/a CVE-2017-13301 | A-66498711       [2] | DoS | Moderate | 8.0
- n/a CVE-2017-13302 | A-69969749 | DoS | Moderate | 8.0

Kernel components

- n/a CVE-2017-13304 | A-70576999* | ID | Moderate | mnh_sm driver - not found
- [x] CVE-2017-13305 | A-70526974* | ID | Moderate | encrypted-keys
  https://android.googlesource.com/kernel/msm/+/c9bd2cd91770bdb94b43640a770c8ac6728c028a
- n/a CVE-2017-17449 | A-70980949         Upstream kernel | ID | Moderate | netlink tap
- n/a CVE-2017-13306 | A-70295063* | EoP | Moderate | mnh driver - not found
- n/a CVE-2017-13307 | A-69128924* | EoP | Moderate | pci sysfs - not found
- [x] CVE-2017-17712 | A-71500434          Upstream kernel | EoP | Moderate | net ipv4
- [x] CVE-2017-15115 | A-70217214          Upstream kernel | EoP | Moderate | sctp

Qualcomm components

- n/a CVE-2018-3598 | A-71501698          QC-CR#1097390 | ID | Moderate | camera_v2 driver
- n/a CVE-2018-5826 | A-69128800*         QC-CR#2157283 | ID | Moderate | qcacld-3.0 hdd driver - not found
- n/a CVE-2017-15853 | A-65853393*         QC-CR#2116517         QC-CR#2125577 | ID | Moderate | WLAN
https://android.googlesource.com/kernel/msm/+/5d25d8a24d2f172c1124cab8c98827c3009d5dc7
- n/a CVE-2018-3584 | A-64610600*         QC-CR#2142046 | ID | Moderate | rmnet_usb - not found
- n/a CVE-2017-8269 | A-33967002*         QC-CR#2013145         QC-CR#2114278 | ID | Moderate | IPA driver
https://android.googlesource.com/kernel/msm/+/bfa5b61b739a2d0dcba5ce68a77ea82dee77e8d5
- [x] CVE-2017-15837 | A-64403015*         QC-CR#2116387 | ID | Moderate | NL80211 driver
https://android.googlesource.com/kernel/msm/+/76be981024d057b73798371608efa3d5c1f89780
- n/a CVE-2018-5823 | A-72957335          QC-CR#2139436 | EoP | Moderate | WLAN
- [x] CVE-2018-5825 | A-72957269         QC-CR#2151146        [2]        [3] | EoP | Moderate | IPA driver
- n/a CVE-2018-5824 | A-72957235         QC-CR#2149399        [2] | EoP | Moderate | WLAN
- n/a CVE-2018-5827 | A-72956920          QC-CR#2161977 | EoP | Moderate | WLAN
- n/a CVE-2018-5822 | A-71501692          QC-CR#2115221 | EoP | Moderate | QC WLAN
- n/a CVE-2018-5821 | A-71501687          QC-CR#2114363 | EoP | Moderate | modem driver
- n/a CVE-2018-5820 | A-71501686          QC-CR#2114336 | EoP | Moderate | Modem driver
- n/a CVE-2018-3599 | A-71501666          QC-CR#2047235 | EoP | Moderate | Qualcomm Core Services
- n/a CVE-2018-3596 | A-35263529*         QC-CR#640898 | EoP | Moderate | WLAN - not found
- n/a CVE-2018-3568 | A-72957136          QC-CR#2152824 | EoP | Moderate | WLAN
- n/a CVE-2018-3567 | A-72956997         QC-CR#2147119        [2] | EoP | Moderate | WLAN
- n/a CVE-2017-15855 | A-72957336          QC-CR#2149501 | EoP | Moderate | WLAN
- n/a CVE-2018-5828 | A-71501691          QC-CR#2115207 | EoP | Moderate | QC WLAN
- n/a CVE-2017-15836 | A-71501693          QC-CR#2119887 | EoP | Moderate | QC WLAN
- n/a CVE-2017-14890 | A-71501695          QC-CR#2120751 | EoP | Moderate | QC WLAN
- n/a CVE-2017-14894 | A-71501694          QC-CR#2120424 | EoP | Moderate | QC WLAN
- n/a CVE-2017-14880 | A-68992477          QC-CR#2078734        [2] | EoP | Moderate | IPA WAN driver
- n/a CVE-2017-11075 | A-70237705          QC-CR#2098332 | EoP | Moderate | Audio DSP driver

Quite a big one, as always.

EDIT MSe1969:
To apply **CVE-2018-3599** (Qualcomm core), this patch needs to be applied first:
https://source.codeaurora.org/quic/la/kernel/msm-3.18/commit/drivers/char/diag/diag_dci.c?h=LA.BR.5.6&id=f63a08b1d28db77b48bd58391dd71248f39f859b
However, this patch does not compile due to missing debug macro definition, so I think it is N/A, since it is from 3.18 kernel and it may not be worth trying to backport... - what do you think?

**Comment by MSe1969** [comment]
I've edited the ASB 2018.04 section (1st section) as follows:
a. Stuff, which really is N/A is marked N/A
b. Already applied patches are checked [x]
c. Patches to be applied are unchecked [ ]

Please note, that system/bt is **external/bluetooth/bluedroid** in LP and that the .cc files are .c files!
See EDIT in section

**Comment by Micha-Btz** [comment]
https://access.redhat.com/security/cve/cve-2017-17449
https://cateee.net/lkddb/web-lkddb/NLMON.html
cve-2017-17449 only affected if CONFIG_NLMON is set. This is  from Kernel 3.11 on. So I would say, we are not affected.

At CVE-2017-13278 I will take a closer look today. The patch doesn't apply cleanly.

**Comment by MSe1969** [comment]
Okay... - updated and applied all patches, as applicable, except for CVE-2017-13278.
Test build compiled fine, so I'll start to test on my side. (Version string not yet set)

Test areas for our regression testing would be:
- GPS
- E-Mail attachment handling (AOSP mail app and custom mail app)
- Usual media playback (Youtube etc.)
- Bluetooth
- TTS (e.g. use navigation app through PICO TTS <not Google TTS!!!>)
- Look for unexpected crashes (--> Kernel)

**Comment by Micha-Btz** [comment]
I wasn't able to patch CVE-2017-13278 have had always an compile error. Have also build and test right now.

**Comment by MSe1969** [comment]
I took CVE-2017-13278 from cm-11.0 LineageOS Gerrit, as it is a true backport. It does not yet compile on cm-11.0 either, so I hope to be able to use their solution, once they found it ;)

**Comment by MSe1969** [comment]
My test results so far:
- Navigation (osmand~ app) in car, connected to Bluetooth: OK, this is good for the GPS patch,  (svox), and BT
- Regular phone calls
- Playing music in car (Bluetooth)
- Playing videos via NewPipe app from YT
 
All good so far

**Comment by MSe1969** [comment]
Outstanding items for April ASB
1. TESTING
- Testing E-Mail attachment patch
- Testing Bluetooth: Pairing with device containing line break in its name (I can't test that)
2. PATCHES
- CVE-2017-13278 (wait for solution in cm-11.0 ?)
- Decision on kernel patch CVE-2018-3599

**Comment by Micha-Btz** [comment]
CVE-2018-3599 I would say, leave it out.

**Comment by Micha-Btz** [comment]
Test areas for our regression testing would be:

-     GPS
-     E-Mail attachment handling (AOSP mail app and custom mail app)
-     Usual media playback (Youtube etc.)
-     Bluetooth
-     TTS (e.g. use navigation app through PICO TTS <not Google TTS!!!>)
-     Look for unexpected crashes (--> Kernel)

For me no problems. But we should add the GPS fix before releasing.

**Comment by MSe1969** [comment]
Will have a look only tomorrow, had Internet outage yesterday and no time today

**Comment by MSe1969** [comment]
sorry - didn't really find time this week and also away now.
I can publish/ship the April build Sunday night, if that is ok for you.

**Comment by Micha-Btz** [comment]
For me it is ok. When you don't have time I also can ship the release.

**Comment by MSe1969** [comment]
As you like, if you would like to ship, please go ahead. Two remarks: 
- don't forget to announce M65 for system webview
- you can include the telephony patch, it won't harm, but still needs another fix

**Comment by MSe1969** [comment]
I've updated our thread, merged the test branch into stable branch, so we can close this issue.
There is however one patch yet left out: CVE-2017-13278
I'll put in into our "left out patches" issue and keep an eye on the backporting efforts in the cm-11.0 gerrit
