### ISSUE TITLE
ASB 2019.09

### ISSUE THREAD

**Issue by MSe1969** [cm12-amami/discussion#57]
ASB 2019.09 is out (but no source links yet)

**Comment by MSe1969** [comment]
***2019-09-01***
**Framework**
- [x] CVE-2019-2123  A-34175893 [2][3][4]  EoP  High - applied
- n/a CVE-2019-2174  A-132927376  EoP  High - LP has no AppOps in Sensors
- n/a CVE-2019-2175  A-135551349  EoP  High - Android 9
- n/a CVE-2019-9254  A-130164289  EoP  High - Android 10
- n/a CVE-2019-2103  A-120610669[2]  ID  High - Android 9

**Media Framework**
- n/a CVE-2019-2176  A-134420911  RCE  Critical - Android 8 and above
- n/a CVE-2019-2108  A-130025324  RCE  Critical - Android 10

**System**
- n/a CVE-2019-2177  A-132456322  RCE  High - no HidProfile.java
- n/a CVE-2019-2115  A-129768470 [2]  EoP  High - no Gatekeeper
- [x] CVE-2019-2178  A-124462242  EoP  High - applied
- [x] CVE-2019-2179  A-126200054  ID  High - applied
- n/a CVE-2019-2180  A-110899492  ID  High - Android 8, 9
- [x] CVE-2019-2124  A-127320867 [2][3]  ID - applied 

***2019-09-05***
**Kernel**
- n/a CVE-2018-20669  A-135368228*  EoP  High - i915 driver (x86 only)
- n/a CVE-2019-2181  A-130571081  EoP  High - Code to be fixed not present

**Qualcomm**
- n/a CVE-2017-17768  A-67748905 QC-CR#2127172  High - LK bootloader
- n/a CVE-2019-2283  A-127513124 QC-CR#2355425 High - no glink_smem_native_xprt.c
- n/a CVE-2019-2316  A-129848922 QC-CR#2358397 High - no avb_slot_verify.c
- [x] CVE-2019-10491  A-132171785 QC-CR#2380709 [2] High - applied
- n/a CVE-2019-10505  A-123533258 QC-CR#2231755 High - qcacld-3.0 n/a
- n/a CVE-2019-10505  A-132171579 QC-CR#2246426 High - qcacld-3.0 n/a
- n/a CVE-2019-2323  A-132173424 QC-CR#2370589 High - no ice.c
- n/a CVE-2019-2324  A-132173296 QC-CR#2372292 High - code differs (no corresp. lock)
- n/a CVE-2019-2325  A-132171784 QC-CR#2372302 [2] High - code to be fixed not present
- [x] CVE-2019-2331  A-132172905 QC-CR#2380697 [2] High - applied
- n/a CVE-2019-2332  A-132171963 QC-CR#2380699 [2] High - coding differs too much
- n/a CVE-2019-10512  A-134439528 QC-CR#2380702 [2] High - code not present
- n/a CVE-2019-10515  A-134440011 QC-CR#2366038 [2] High - code not present
- [x] CVE-2019-10524  A-134440735 QC-CR#2422233 [2][3] High - applied
- n/a CVE-2019-10529  A-134439992 QC-CR#2442261 High - code not present
- n/a CVE-2019-10531  A-134441415 QC-CR#2402890 [2] High - kernel/lk
- n/a CVE-2018-11891  A-134440013 QC-CR#2288859 High - no func update_fils_data

***Pixel/Nexus***
**Broadcomm**
- n/a CVE-2019-9426  A-110460199*  EoP  Moderate - not found

**Kernel**
- n/a CVE-2019-9345  A-27915347*  EoP  High - no sdcardfs
- n/a CVE-2019-9461  A-120209610*  ID  High - not found
- n/a CVE-2019-9248  A-120279144*  EoP  Moderate - not found
- n/a CVE-2019-9270  A-65123745*  EoP  Moderate - not found
- n/a CVE-2019-2182  A-128700140 EoP  Moderate - arm64
- n/a CVE-2019-9271  A-69006201*  EoP  Moderate - not found
- n/a CVE-2019-9273  A-70241598*  EoP  Moderate - not found
- n/a CVE-2019-9274  A-70809925*  EoP  Moderate - not found
- n/a CVE-2019-9275  A-71508439*  EoP  Moderate - not found
- n/a CVE-2019-9276  A-70294179*  EoP  Moderate - not found
- n/a CVE-2019-9441  A-69006882*  EoP  Moderate - not found
- n/a CVE-2019-9442  A-69808778*  EoP  Moderate - not found
- n/a CVE-2019-9443  A-70896844*  EoP  Moderate - not found
- n/a CVE-2019-9446  A-118617506*  EoP  Moderate - not found
- n/a CVE-2019-9447  A-119120571 EoP  Moderate - no fts.c
- n/a CVE-2019-9448  A-120141999 EoP  Moderate - no fts.c
- n/a CVE-2019-9450  A-120141034 EoP  Moderate - no fts.c
- n/a CVE-2019-9451  A-120211415 EoP  Moderate - no sec_cmd.c
- n/a CVE-2019-9454  A-129148475 EoP  Moderate - no i2c-core-smbus.c
- [x] CVE-2019-9456  A-71362079 EoP  Moderate - applied
- n/a CVE-2019-9457  A-116716935 EoP  Moderate - coding differs
- n/a CVE-2019-9458  A-117989855 EoP  Moderate - coding differs
- [x] CVE 2019-8912  A-125367761 EoP  Moderate - applied
- n/a CVE-2018-18397  A-124036248 EoP  Moderate - no userfaultfd.c
- [x] CVE-2018-14614  A-116406552 EoP  Moderate - applied
- [x] CVE-2018-1000199  A-110918800 EoP  Moderate - applied
- n/a CVE-2018-13096  A-113148557 EoP  Moderate - no func f2fs_inode_chksum_set
- [x] CVE-2018-5803  A-112406370 DoS  Moderate - applied
- n/a CVE-2019-2189  A-112312381  EoP  Moderate - prebuilt image f. bonito kernel
- n/a CVE-2019-2188  A-112309571*  EoP  Moderate - not found
- n/a CVE-2017-16939  A-70521013 EoP  Moderate - 'start' not defined
- [x] CVE-2018-20169  A-120783657 ID  Moderate - applied
- n/a CVE-2019-9245  A-120491338 ID  Moderate - no func read_xattr_block
- n/a CVE-2019-9444  A-78597155 ID  Moderate - no sync_debug.c
- n/a CVE-2019-9445  A-118153030 ID  Moderate - (f2fs merge commit)
- n/a CVE-2019-9449  A-120141031 ID  Moderate - no fts.c
- n/a CVE-2019-9452  A-120211708 ID  Moderate - no fts.c
- n/a CVE-2019-9453  A-126558260 ID  Moderate - coding differs
- n/a CVE-2019-9455  A-121035792 ID  Moderate - no videobuf2-v4l2.c
- [x] CVE-2018-19985  A-131963918 ID  Moderate - applied
- [x] CVE-2018-20511  A-123742046 ID  Moderate - applied
- [x] CVE-2018-1000204  A-113096593 ID  Moderate -applied

**Qualcomm**
- n/a CVE-2017-14888  A-70237718 Moderate - no lim_process_sme_req_messages.c
- n/a CVE-2018-3573  A-72957667 Moderate - Bootloader
- n/a CVE-2017-15844  A-67749071 Moderate - kernel/lk
- n/a CVE-2018-3574  A-72957321 [2][3]  Moderate - code differs
- n/a CVE-2018-5861  A-77527684 Moderate - Bootloader
- n/a CVE-2018-11302  A-109741923 Moderate - no csr_api.h
- n/a CVE-2018-5919  A-65423852 Moderate - code differs
- n/a CVE-2018-11818  A-111127974 Moderate - code differs
- [x] CVE-2018-11832  A-111127793 Moderate - applied
- n/a CVE-2018-11893  A-111127990 Moderate - qcacld 3.0
- n/a CVE-2018-11919  A-79217930 [2][3] Moderate - no msm_bus_fabric_adhoc.c
- [x] CVE-2018-11939  A-77237693 Moderate - applied
- n/a CVE-2018-11823  A-112277122 Moderate - no lpm-levels-of.c
- n/a CVE-2018-11929  A-112277631 Moderate - no lim_api.c
- n/a CVE-2018-11943  A-72117228 Moderate - Bootloader
- n/a CVE-2018-11947  A-112277911 [2] Moderate - no htt_h2t.c / ol_txrx.c
- n/a CVE-2018-11947  A-112278406 Moderate - no ol_txrx.c
- n/a CVE-2018-11942  A-112278151 Moderate - no wmi_unified.c
- n/a CVE-2018-11983  A-80095430 Moderate - no func diag_cmd_set_all_msg_mask
- n/a CVE-2018-11984  A-80435805 Moderate - coding differs
- n/a CVE-2018-11987  A-70638103 Moderate - fix already present
- n/a CVE-2018-11985  A-114041193 Moderate - Bootloader
- [x] CVE-2018-11988  A-114041748 [2] Moderate - applied
- [x] CVE-2018-11986  A-62916765 Moderate - applied
- [x] CVE-2018-12010  A-62711756 Moderate - applied
- n/a CVE-2018-12006  A-77237704 Moderate - no gralloc
- n/a CVE-2018-13893  A-80302295 Moderate - coding differs
- [x] CVE-2018-12011  A-109697864 Moderate - applied
- n/a CVE-2018-13912  A-119053502 Moderate - coding differs
- n/a CVE-2018-13913  A-119053530 [2] Moderate - compile error due to type
- n/a CVE-2018-3564  A-119052383 Moderate - no func fastrpc_file_free
- n/a CVE-2019-2248  A-122474006 Moderate - kernel/lk
- n/a CVE-2019-2277  A-127512945 Moderate - no func hdd_dns_make_name_query
- n/a CVE-2019-2263  A-116024809 Moderate - code differs
- n/a CVE-2019-2345  A-110849476 Moderate - no msm_jpeg_dma_dev.c
- n/a CVE-2019-2306  A-115907574 Moderate - no libgralloc
- n/a CVE-2019-2299  A-117988970 Moderate - no wmi_unified_tlv.c
- n/a CVE-2019-2312  A-117885392 Moderate - no func hdd_validate_avoid_freq_chanlist
- n/a CVE-2019-2314  A-120028144 Moderate - no dp_debug.c
- n/a CVE-2019-2314  A-120029095 Moderate - no dp_debug.c
- n/a CVE-2019-2302  A-130565935 Moderate - no wlan_hdd_ocb.c
- n/a CVE-2019-10506  A-117885703 Moderate - no func wlan_hdd_validate_avoid_freq
- [x] CVE-2018-13890  A-111274306 Moderate - applied
- n/a CVE-2019-10507  A-132170503 Moderate - no wma_scan_roam.c / wlan_hdd_ext_scan.c
- [x] CVE-2019-10508  A-132173922 Moderate - applied, same as CVE-2018-13890
- n/a CVE-2019-2284  A-132173427 Moderate - no cam_req_mgr_core.c
- [x] CVE-2019-2333  A-132171964 [2][3] Moderate - applied
- [x] CVE-2019-2341  A-132172264 Moderate - applied
- [x] CVE-2019-10497  A-132173298 Moderate - applied
- n/a CVE-2019-10542  A-134440623 Moderate - no ol_fw.c
- n/a CVE-2019-10502  A-134441002 Moderate - no cam_lrme_hw_mgr.c
- n/a CVE-2019-10528  A-63528466 [2] Moderate - code differs
- n/a CVE-2018-11825  A-117985523 Moderate - no wmi_unified_tlv.c

**Comment by MSe1969** [comment]
Test build running...

**Comment by MSe1969** [comment]
Build shipped, closing issue
